services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_USER}"
      POSTGRES_USER: "${POSTGRES_PASSWORD}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      start_interval: 3s
      start_period: 30s
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  migrations:
    build:
      context: .
      dockerfile: migrations.dockerfile
      args:
        RUST_VERSION: ${RUST_VERSION}
        ALPINE_VERSION: "3.21"
        SQLX_CLI_VERSION: "0.8.6"
    depends_on:
      postgres:
        condition: service_healthy
    command: >-
      database reset
        --source /migrations
        --no-dotenv
        --database-url "${DATABASE_INTERNAL_DSN}"
        -y
    volumes:
      - ${MIGRATIONS_PATH}:/migrations:ro
